# docker-compose.yml
services:
  livekit:
    image: livekit/livekit-server
    network_mode: "host" # Use host networking
    volumes:
      - ./livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml
